"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import {
  Video,
  GitBranch,
  MessageSquare,
  Zap,
  ArrowRight,
  Play,
  Shield,
} from "lucide-react";

const fadeUp = {
  initial: { opacity: 0, y: 24 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.5 },
};

const stagger = {
  animate: {
    transition: {
      staggerChildren: 0.08,
    },
  },
};

const features = [
  {
    icon: Video,
    title: "Screen Recording",
    description:
      "Capture your entire screen, specific window, or browser tab. Pause, resume, and download recordings in WebM.",
  },
  {
    icon: GitBranch,
    title: "Workflow Review",
    description:
      "Browse workflows generated by OpenJarvis and Opus. View steps, status timelines, and metadata.",
  },
  {
    icon: MessageSquare,
    title: "Comments to Opus",
    description:
      "Write text comments about any workflow and send them directly to Opus for AI-driven improvements.",
  },
  {
    icon: Shield,
    title: "Privacy-First",
    description:
      "Record locally, upload only when ready. No data stored until you choose to share it.",
  },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen landing-gradient landing-grid overflow-hidden">
      {/* Nav */}
      <motion.header
        initial={{ opacity: 0, y: -16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="fixed top-0 left-0 right-0 z-50 border-b border-surface-200/60 bg-white/70 backdrop-blur-xl"
      >
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 group">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-brand-500 to-brand-700 flex items-center justify-center shadow-sm group-hover:shadow-md transition-shadow">
              <Zap className="w-4 h-4 text-white" />
            </div>
            <span className="font-display text-lg font-medium tracking-tight text-surface-900">
              OpenJarvis
            </span>
          </Link>
          <nav className="flex items-center gap-4 sm:gap-6">
            <Link
              href="/dashboard"
              className="hidden sm:inline text-sm font-medium text-surface-600 hover:text-surface-900 transition-colors"
            >
              Dashboard
            </Link>
            <Link
              href="/recorder"
              className="hidden sm:inline text-sm font-medium text-surface-600 hover:text-surface-900 transition-colors"
            >
              Recorder
            </Link>
            <Link
              href="/workflows"
              className="hidden sm:inline text-sm font-medium text-surface-600 hover:text-surface-900 transition-colors"
            >
              Workflows
            </Link>
            <Link
              href="/dashboard"
              className="btn-primary text-sm px-4 py-2 shrink-0"
            >
              Get started
              <ArrowRight className="w-4 h-4" />
            </Link>
          </nav>
        </div>
      </motion.header>

      {/* Hero */}
      <section className="pt-32 pb-24 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-brand-50 text-brand-700 text-sm font-medium mb-8 border border-brand-100"
          >
            <span className="w-2 h-2 rounded-full bg-brand-500 animate-pulse" />
            Screen recording & workflow review
          </motion.div>
          <motion.h1
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="text-4xl sm:text-5xl lg:text-6xl font-display font-normal tracking-tight text-surface-900 leading-[1.1]"
          >
            Capture. Review.{" "}
            <span className="text-gradient">Improve.</span>
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="mt-6 text-lg sm:text-xl text-surface-600 max-w-2xl mx-auto leading-relaxed"
          >
            Record your screen, extract workflows with AI, and send feedback to
            Opus — all in one polished experience.
          </motion.p>
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.3 }}
            className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4"
          >
            <Link
              href="/dashboard"
              className="btn-primary px-6 py-3 text-base font-medium rounded-xl shadow-md hover:shadow-lg transition-all"
            >
              Open dashboard
              <ArrowRight className="w-4 h-4" />
            </Link>
            <Link
              href="/recorder"
              className="btn-secondary px-6 py-3 text-base font-medium rounded-xl inline-flex items-center gap-2"
            >
              <Play className="w-4 h-4" />
              Start recording
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section className="py-24 px-4 sm:px-6 lg:px-8">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial="initial"
            whileInView="animate"
            viewport={{ once: true, margin: "-80px" }}
            variants={stagger}
            className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6"
          >
            {features.map((feature, i) => (
              <motion.div
                key={feature.title}
                variants={fadeUp}
                transition={{ duration: 0.4 }}
                className="group relative p-6 rounded-2xl bg-white/80 backdrop-blur border border-surface-200/60 shadow-sm hover:shadow-medium hover:border-brand-200/60 transition-all duration-300"
              >
                <div className="w-10 h-10 rounded-xl bg-brand-50 flex items-center justify-center text-brand-600 group-hover:bg-brand-100 transition-colors mb-4">
                  <feature.icon className="w-5 h-5" />
                </div>
                <h3 className="font-semibold text-surface-900 mb-2">
                  {feature.title}
                </h3>
                <p className="text-sm text-surface-600 leading-relaxed">
                  {feature.description}
                </p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="max-w-3xl mx-auto text-center p-12 rounded-3xl bg-gradient-to-br from-brand-500/10 via-brand-400/5 to-transparent border border-brand-200/40"
        >
          <h2 className="text-2xl sm:text-3xl font-display font-normal tracking-tight text-surface-900">
            Ready to streamline your workflow?
          </h2>
          <p className="mt-3 text-surface-600">
            Jump in and start recording. No account required.
          </p>
          <Link
            href="/dashboard"
            className="btn-primary mt-6 px-6 py-3 text-base font-medium inline-flex"
          >
            Go to dashboard
            <ArrowRight className="w-4 h-4" />
          </Link>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="py-12 px-4 sm:px-6 lg:px-8 border-t border-surface-200/60">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-md bg-gradient-to-br from-brand-500 to-brand-700 flex items-center justify-center">
              <Zap className="w-3 h-3 text-white" />
            </div>
            <span className="font-display text-sm text-surface-600">
              OpenJarvis
            </span>
          </div>
          <nav className="flex items-center gap-8">
            <Link
              href="/dashboard"
              className="text-sm text-surface-500 hover:text-surface-900 transition-colors"
            >
              Dashboard
            </Link>
            <Link
              href="/recorder"
              className="text-sm text-surface-500 hover:text-surface-900 transition-colors"
            >
              Recorder
            </Link>
            <Link
              href="/workflows"
              className="text-sm text-surface-500 hover:text-surface-900 transition-colors"
            >
              Workflows
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  );
}
