"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import {
  Video,
  GitBranch,
  MessageSquare,
  Zap,
  ArrowRight,
  Play,
  Shield,
} from "lucide-react";

const fadeUp = {
  initial: { opacity: 0, y: 24 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.5 },
};

const stagger = {
  animate: {
    transition: {
      staggerChildren: 0.08,
    },
  },
};

const features = [
  {
    icon: Video,
    title: "Screen Recording",
    description:
      "Capture your entire screen, specific window, or browser tab. Pause, resume, and download recordings in WebM.",
  },
  {
    icon: GitBranch,
    title: "Workflow Review",
    description:
      "Browse workflows generated by OpenJarvis and Opus. View steps, status timelines, and metadata.",
  },
  {
    icon: MessageSquare,
    title: "Comments to Opus",
    description:
      "Write text comments about any workflow and send them directly to Opus for AI-driven improvements.",
  },
  {
    icon: Shield,
    title: "Privacy-First",
    description:
      "Record locally, upload only when ready. No data stored until you choose to share it.",
  },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen landing-gradient landing-grid overflow-hidden">
      {/* Nav */}
      <motion.header
        initial={{ opacity: 0, y: -16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="fixed top-0 left-0 right-0 z-50 border-b border-surface-200/60 dark:border-surface-700/60 bg-white/80 dark:bg-surface-900/80 backdrop-blur-xl"
      >
        <div className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 xl:px-10 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5 group">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-brand-500 to-brand-700 flex items-center justify-center shadow-sm group-hover:shadow-md group-hover:scale-105 transition-all duration-300">
              <Zap className="w-4 h-4 text-white" />
            </div>
            <span className="font-display text-lg font-medium tracking-tight text-surface-900 dark:text-surface-100">
              OpenJarvis
            </span>
          </Link>
          <nav className="flex items-center">
            <Link
              href="/dashboard"
              className="btn-primary text-sm px-5 py-2.5 rounded-xl shrink-0 font-medium shadow-sm hover:shadow-md transition-all duration-300"
            >
              Get started
              <ArrowRight className="w-4 h-4" />
            </Link>
          </nav>
        </div>
      </motion.header>

      {/* Hero */}
      <section className="pt-36 pb-28 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="inline-flex items-center gap-2.5 px-5 py-2.5 rounded-full bg-white/90 dark:bg-surface-900/90 backdrop-blur border border-surface-200/80 shadow-sm mb-10"
          >
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-brand-500 opacity-75" />
              <span className="relative inline-flex rounded-full h-2 w-2 bg-brand-500" />
            </span>
            <span className="text-sm font-medium text-surface-700 dark:text-surface-300">
              Screen recording & workflow review
            </span>
          </motion.div>
          <motion.h1
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="text-4xl sm:text-5xl lg:text-7xl font-display font-normal tracking-tight text-surface-900 dark:text-surface-100 leading-[1.08]"
          >
            Capture. Review.{" "}
            <span className="text-gradient">
              Improve.
            </span>
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="mt-8 text-lg sm:text-xl text-surface-600 dark:text-surface-400 max-w-2xl mx-auto leading-relaxed"
          >
            Record your screen, extract workflows with AI, and send feedback to
            Opus — all in one polished experience.
          </motion.p>
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.3 }}
            className="mt-12 flex flex-col sm:flex-row items-center justify-center gap-4"
          >
            <Link
              href="/dashboard"
              className="w-full sm:w-auto btn-primary px-8 py-3.5 text-base font-medium rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 hover:scale-[1.02] active:scale-[0.98]"
            >
              Open dashboard
              <ArrowRight className="w-4 h-4" />
            </Link>
            <Link
              href="/recorder"
              className="w-full sm:w-auto btn-secondary px-8 py-3.5 text-base font-medium rounded-xl inline-flex items-center justify-center gap-2 border-2 hover:border-brand-300 dark:hover:border-brand-700/50 hover:bg-brand-50/50 dark:hover:bg-brand-900/10 transition-all duration-300 hover:scale-[1.02] active:scale-[0.98]"
            >
              <Play className="w-4 h-4 fill-current" />
              Start recording
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section className="py-28 px-4 sm:px-6 lg:px-8">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <p className="text-sm font-semibold text-surface-500 uppercase tracking-wider">
              Features
            </p>
            <h2 className="mt-2 text-2xl sm:text-3xl font-display font-normal tracking-tight text-surface-900 dark:text-surface-100">
              Everything you need
            </h2>
          </motion.div>
          <motion.div
            initial="initial"
            whileInView="animate"
            viewport={{ once: true, margin: "-80px" }}
            variants={stagger}
            className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6"
          >
            {features.map((feature) => (
              <motion.div
                key={feature.title}
                variants={fadeUp}
                transition={{ duration: 0.4 }}
                className="group relative p-6 sm:p-7 rounded-2xl bg-white dark:bg-surface-900/80 backdrop-blur border border-surface-200/80 dark:border-surface-700/80 shadow-soft hover:shadow-medium hover:border-brand-200/60 dark:hover:border-brand-800/40 transition-all duration-300 hover:scale-[1.02] hover:-translate-y-1"
              >
                <div className="absolute inset-0 rounded-2xl bg-gradient-to-br from-brand-500/[0.03] to-transparent opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none" />
                <div className="relative">
                  <div className="w-12 h-12 rounded-xl bg-brand-50 dark:bg-brand-900/30 flex items-center justify-center text-brand-600 dark:text-brand-400 group-hover:bg-brand-100 dark:group-hover:bg-brand-900/50 transition-colors mb-5 shadow-sm">
                    <feature.icon className="w-6 h-6" />
                  </div>
                  <h3 className="font-semibold text-surface-900 dark:text-surface-100 mb-2 text-base">
                    {feature.title}
                  </h3>
                  <p className="text-sm text-surface-600 dark:text-surface-400 leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-28 px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="max-w-3xl mx-auto text-center p-12 sm:p-16 rounded-3xl bg-gradient-to-br from-brand-500/15 via-brand-400/8 to-transparent border-2 border-brand-200/50 dark:border-brand-800/30 shadow-soft"
        >
          <h2 className="text-2xl sm:text-4xl font-display font-normal tracking-tight text-surface-900 dark:text-surface-100">
            Ready to streamline your workflow?
          </h2>
          <p className="mt-4 text-surface-600 dark:text-surface-400 text-lg">
            Jump in and start recording. No account required.
          </p>
          <Link
            href="/dashboard"
            className="mt-8 btn-primary px-8 py-3.5 text-base font-medium rounded-xl inline-flex shadow-md hover:shadow-lg transition-all duration-300 hover:scale-[1.02] active:scale-[0.98]"
          >
            Go to dashboard
            <ArrowRight className="w-4 h-4" />
          </Link>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="py-14 px-4 sm:px-6 lg:px-8 border-t border-surface-200/60 dark:border-surface-700/60">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-center gap-4">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-brand-500 to-brand-700 flex items-center justify-center shadow-sm">
              <Zap className="w-3.5 h-3.5 text-white" />
            </div>
            <span className="font-display text-sm text-surface-600 dark:text-surface-400">
              OpenJarvis
            </span>
          </div>
        </div>
      </footer>
    </div>
  );
}
