import { Workflow, Recording, DashboardStats } from "@/types";

export const mockWorkflows: Workflow[] = [
  {
    id: "wf_001",
    title: "User Onboarding Flow — v2.4",
    description:
      "Automated onboarding sequence generated by Opus that walks new users through account setup, preference configuration, and first-project creation.",
    steps: [
      {
        id: "s1",
        order: 1,
        title: "Welcome Modal Displayed",
        description:
          "System triggers the welcome modal after successful email verification. Includes brand animation and CTA.",
        status: "completed",
      },
      {
        id: "s2",
        order: 2,
        title: "Profile Setup Form",
        description:
          "User fills in display name, avatar upload, and timezone selection. Validation runs on blur.",
        status: "completed",
      },
      {
        id: "s3",
        order: 3,
        title: "Workspace Configuration",
        description:
          "Prompt user to name their workspace, invite teammates, and select a color theme.",
        status: "completed",
      },
      {
        id: "s4",
        order: 4,
        title: "First Project Creation",
        description:
          "Guide user through creating their first project using a template or blank canvas.",
        status: "pending",
      },
      {
        id: "s5",
        order: 5,
        title: "Completion & Dashboard Redirect",
        description:
          "Show success confetti, then redirect to the main dashboard with a contextual tooltip tour.",
        status: "pending",
      },
    ],
    metadata: {
      source: "Opus",
      version: "2.4.0",
      executionTime: 3420,
      model: "opus-4",
    },
    createdAt: "2026-02-15T08:30:00Z",
    updatedAt: "2026-02-15T09:15:00Z",
    recordingId: "rec_001",
    tags: ["onboarding", "user-flow", "critical-path"],
  },
  {
    id: "wf_002",
    title: "Data Export Pipeline",
    description:
      "OpenJarvis-generated workflow for exporting user analytics data to CSV and PDF formats with scheduled delivery.",
    steps: [
      {
        id: "s1",
        order: 1,
        title: "Select Date Range",
        description:
          "User selects export date range via calendar picker. Supports preset ranges (7d, 30d, 90d, custom).",
        status: "completed",
      },
      {
        id: "s2",
        order: 2,
        title: "Choose Export Format",
        description:
          "Toggle between CSV, PDF, and JSON. Each format shows a live preview of column mapping.",
        status: "completed",
      },
      {
        id: "s3",
        order: 3,
        title: "Configure Filters",
        description:
          "Optional step to filter by team, project, or user role before export.",
        status: "completed",
      },
      {
        id: "s4",
        order: 4,
        title: "Queue Export Job",
        description:
          "Submit the export job to the background processor. Show progress indicator and estimated time.",
        status: "failed",
      },
      {
        id: "s5",
        order: 5,
        title: "Download or Email Delivery",
        description:
          "Once processing completes, offer direct download or email delivery with a signed link.",
        status: "pending",
      },
    ],
    metadata: {
      source: "OpenJarvis",
      version: "1.8.2",
      executionTime: 8750,
      model: "claw-v3",
    },
    createdAt: "2026-02-14T14:20:00Z",
    updatedAt: "2026-02-14T16:45:00Z",
    tags: ["data", "export", "analytics"],
  },
  {
    id: "wf_003",
    title: "Permission Escalation Review",
    description:
      "Opus-generated audit workflow for reviewing and approving permission escalation requests from team members.",
    steps: [
      {
        id: "s1",
        order: 1,
        title: "Request Submitted",
        description:
          "Team member submits permission escalation request with justification and scope definition.",
        status: "completed",
      },
      {
        id: "s2",
        order: 2,
        title: "Automated Risk Assessment",
        description:
          "System analyzes the requested permissions against security policies and flags potential risks.",
        status: "completed",
      },
      {
        id: "s3",
        order: 3,
        title: "Manager Review",
        description:
          "Direct manager receives notification and reviews the request with risk assessment context.",
        status: "completed",
      },
      {
        id: "s4",
        order: 4,
        title: "Security Team Approval",
        description:
          "For high-risk escalations, the security team performs a secondary review.",
        status: "completed",
      },
      {
        id: "s5",
        order: 5,
        title: "Permission Applied",
        description:
          "Approved permissions are applied with an automatic 90-day expiry and audit trail entry.",
        status: "completed",
      },
    ],
    metadata: {
      source: "Opus",
      version: "3.1.0",
      executionTime: 1200,
      model: "opus-4",
    },
    createdAt: "2026-02-13T10:00:00Z",
    updatedAt: "2026-02-13T10:30:00Z",
    recordingId: "rec_002",
    tags: ["security", "permissions", "audit"],
  },
  {
    id: "wf_004",
    title: "Invoice Generation & Delivery",
    description:
      "End-to-end invoice creation workflow from OpenJarvis, covering line item assembly through client delivery via email.",
    steps: [
      {
        id: "s1",
        order: 1,
        title: "Pull Billable Items",
        description:
          "Aggregate all billable items from the selected time period across projects and contracts.",
        status: "completed",
      },
      {
        id: "s2",
        order: 2,
        title: "Apply Rates & Discounts",
        description:
          "Calculate totals using contracted rates, apply any volume discounts or credits.",
        status: "completed",
      },
      {
        id: "s3",
        order: 3,
        title: "Generate PDF Invoice",
        description:
          "Render the invoice PDF with company branding, line items, tax calculations, and payment terms.",
        status: "pending",
      },
      {
        id: "s4",
        order: 4,
        title: "Send to Client",
        description:
          "Email the invoice to the client's billing contact with a payment portal link.",
        status: "pending",
      },
    ],
    metadata: {
      source: "OpenJarvis",
      version: "2.0.1",
      executionTime: 5200,
      model: "claw-v3",
    },
    createdAt: "2026-02-12T16:00:00Z",
    updatedAt: "2026-02-12T17:30:00Z",
    tags: ["billing", "invoices", "finance"],
  },
];

export const mockRecordings: Recording[] = [
  {
    id: "rec_001",
    name: "Onboarding Flow Walkthrough",
    duration: 245,
    size: 48_500_000,
    createdAt: "2026-02-15T08:00:00Z",
    status: "uploaded",
  },
  {
    id: "rec_002",
    name: "Permission Escalation Demo",
    duration: 180,
    size: 32_100_000,
    createdAt: "2026-02-13T09:30:00Z",
    status: "uploaded",
  },
  {
    id: "rec_003",
    name: "Dashboard Bug Reproduction",
    duration: 67,
    size: 12_800_000,
    createdAt: "2026-02-11T14:15:00Z",
    status: "ready",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalRecordings: 3,
  totalWorkflows: 4,
  commentsSent: 7,
  totalDuration: 492,
};
