"use client";

import { useState, useEffect } from "react";
import { Workflow } from "@/types";
import { PageHeader } from "@/components/layout/PageHeader";
import { WorkflowList } from "@/components/workflows/WorkflowList";
import { WorkflowDetail } from "@/components/workflows/WorkflowDetail";
import { EmptyState, Skeleton } from "@/components/ui/SharedUI";
import { GitBranch, MousePointerClick } from "lucide-react";

export default function WorkflowsPage() {
  const [workflows, setWorkflows] = useState<Workflow[]>([]);
  const [selected, setSelected] = useState<Workflow | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchWorkflows() {
      try {
        const res = await fetch("/api/workflows");
        const data = await res.json();
        if (data.success) {
          setWorkflows(data.data);
        }
      } catch {
        // fallback handled by empty state
      } finally {
        setLoading(false);
      }
    }
    fetchWorkflows();
  }, []);

  return (
    <>
      <PageHeader
        title="Workflow Review"
        description="Review workflows generated by OpenClaw and Opus, and send comments"
      />

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Workflow List Panel */}
        <div className="lg:col-span-5 xl:col-span-4">
          <div className="sticky top-8">
            <h3 className="text-xs font-semibold text-surface-400 uppercase tracking-wider mb-3 px-1">
              Workflows ({workflows.length})
            </h3>
            {loading ? (
              <div className="space-y-3">
                {[1, 2, 3].map((i) => (
                  <Skeleton key={i} className="h-32 w-full" />
                ))}
              </div>
            ) : workflows.length === 0 ? (
              <EmptyState
                icon={GitBranch}
                title="No workflows yet"
                description="Workflows generated by OpenClaw and Opus will appear here."
              />
            ) : (
              <WorkflowList
                workflows={workflows}
                selectedId={selected?.id ?? null}
                onSelect={setSelected}
              />
            )}
          </div>
        </div>

        {/* Detail Panel */}
        <div className="lg:col-span-7 xl:col-span-8">
          {selected ? (
            <WorkflowDetail workflow={selected} />
          ) : (
            <div className="card-elevated">
              <EmptyState
                icon={MousePointerClick}
                title="Select a workflow"
                description="Choose a workflow from the list to view its details and send a comment to Opus."
              />
            </div>
          )}
        </div>
      </div>
    </>
  );
}
