"use client";

import { useState, useEffect } from "react";
import { Workflow } from "@/types";
import { PageHeader } from "@/components/layout/PageHeader";
import { WorkflowList } from "@/components/workflows/WorkflowList";
import { WorkflowDetail } from "@/components/workflows/WorkflowDetail";
import { EmptyState, Skeleton } from "@/components/ui/SharedUI";
import { GitBranch, MousePointerClick } from "lucide-react";

export default function WorkflowsPage() {
  const [workflows, setWorkflows] = useState<Workflow[]>([]);
  const [selected, setSelected] = useState<Workflow | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchWorkflows() {
      try {
        const res = await fetch("/api/workflows");
        const data = await res.json();
        if (data.success) {
          setWorkflows(data.data);
        }
      } catch {
        // fallback handled by empty state
      } finally {
        setLoading(false);
      }
    }
    fetchWorkflows();
  }, []);

  return (
    <>
      <PageHeader
        title="Workflow Review"
        description="Review workflows generated by OpenJarvis and Opus, and send comments"
      />

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Workflow List Panel */}
        <div className="lg:col-span-5 xl:col-span-4">
          <div className="sticky top-8">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-semibold text-surface-800 dark:text-surface-200">
                Workflows
              </h3>
              <span className="text-xs font-medium text-surface-500 bg-surface-100 dark:bg-surface-800 px-2.5 py-1 rounded-lg">
                {workflows.length}
              </span>
            </div>
            {loading ? (
              <div className="space-y-3">
                {[1, 2, 3].map((i) => (
                  <Skeleton key={i} className="h-36 w-full rounded-2xl" />
                ))}
              </div>
            ) : workflows.length === 0 ? (
              <div className="rounded-2xl border border-surface-200/80 dark:border-surface-700/80 bg-white dark:bg-surface-900 shadow-soft overflow-hidden">
                <EmptyState
                  icon={GitBranch}
                  title="No workflows yet"
                  description="Workflows generated by OpenJarvis and Opus will appear here."
                />
              </div>
            ) : (
              <WorkflowList
                workflows={workflows}
                selectedId={selected?.id ?? null}
                onSelect={setSelected}
              />
            )}
          </div>
        </div>

        {/* Detail Panel */}
        <div className="lg:col-span-7 xl:col-span-8">
          {selected ? (
            <WorkflowDetail workflow={selected} />
          ) : (
            <div className="rounded-2xl border border-surface-200/80 dark:border-surface-700/80 bg-white dark:bg-surface-900 shadow-soft overflow-hidden min-h-[420px] flex items-center justify-center">
              <div className="relative p-12 text-center">
                <div className="absolute inset-0 bg-gradient-to-br from-brand-500/[0.03] via-transparent to-transparent pointer-events-none rounded-2xl" />
                <EmptyState
                  icon={MousePointerClick}
                  title="Select a workflow"
                  description="Choose a workflow from the list to view its details and send a comment to Opus."
                />
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
