"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { cn } from "@/lib/utils";
import {
  Video,
  GitBranch,
  LayoutDashboard,
  Images,
  Monitor,
  Zap,
  ChevronRight,
  ChevronLeft,
  X,
} from "lucide-react";

const ONBOARDING_STORAGE_KEY = "openjarvis-onboarding-dismissed";

const steps = [
  {
    title: "Welcome to OpenJarvis",
    subtitle: "Your screen recording & workflow review platform",
    description:
      "OpenJarvis helps you record your screen, extract key moments as screenshots, and share feedback with Opus. Collaborate seamlessly on workflows generated by OpenJarvis and Opus.",
    icon: Zap,
    gradient: "from-amber-500 to-orange-600",
  },
  {
    title: "Record Your Screen",
    subtitle: "Flexible capture options",
    description:
      "Record your entire screen, a specific application window, or a single browser tab. Pause and resume anytime, then download or upload your recording. All recordings are saved as WebM.",
    icon: Video,
    features: ["Entire screen, window, or tab", "Pause / resume / stop", "Download or upload"],
  },
  {
    title: "Extract & Share Screenshots",
    subtitle: "One frame per second",
    description:
      "Automatically extract one screenshot for every second of your recording. Preview them in a gallery, then send them to Opus with optional workflow and recording IDs.",
    icon: Images,
    features: ["1 frame per second", "View before sending", "Send to Opus"],
  },
  {
    title: "Review Workflows",
    subtitle: "Browse and comment",
    description:
      "Explore workflows generated by OpenJarvis and Opus. View step-by-step details, status, and metadata. Send text comments directly to Opus for any workflow.",
    icon: GitBranch,
    features: ["Workflow list & details", "Step status timeline", "Comments to Opus"],
  },
  {
    title: "Dashboard Overview",
    subtitle: "Stay on top of activity",
    description:
      "Your home base: total recordings, workflows, comments sent, and total duration. See recent activity and jump straight into a new recording.",
    icon: LayoutDashboard,
    features: ["Stats at a glance", "Recent activity feed", "Quick new recording"],
  },
];

export function OnboardingOverlay() {
  const [isVisible, setIsVisible] = useState(false);
  const [currentStep, setCurrentStep] = useState(0);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    try {
      const dismissed = localStorage.getItem(ONBOARDING_STORAGE_KEY);
      if (!dismissed) setIsVisible(true);
    } catch {
      setIsVisible(false);
    }
  }, []);

  const dismiss = () => {
    try {
      localStorage.setItem(ONBOARDING_STORAGE_KEY, "true");
      setIsVisible(false);
    } catch {
      setIsVisible(false);
    }
  };

  const next = () => {
    if (currentStep < steps.length - 1) {
      setCurrentStep(currentStep + 1);
    } else {
      dismiss();
    }
  };

  const prev = () => {
    if (currentStep > 0) setCurrentStep(currentStep - 1);
  };

  if (!mounted || !isVisible) return null;

  const step = steps[currentStep];
  const isLast = currentStep === steps.length - 1;
  const isFirst = currentStep === 0;
  const Icon = step.icon;

  return (
    <div
      className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"
      role="dialog"
      aria-modal="true"
      aria-labelledby="onboarding-title"
      aria-describedby="onboarding-description"
    >
      <div className="card-elevated w-full max-w-lg max-h-[90vh] overflow-hidden flex flex-col animate-fade-in shadow-xl">
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-surface-200 dark:border-surface-700">
          <div className="flex items-center gap-2">
            <div
              className={cn(
                "w-10 h-10 rounded-xl flex items-center justify-center",
                "bg-gradient-to-br from-brand-500 to-brand-700"
              )}
            >
              <Zap className="w-5 h-5 text-white" />
            </div>
            <span className="font-display text-lg font-medium text-surface-800 dark:text-surface-200">
              OpenJarvis
            </span>
          </div>
          <button
            type="button"
            onClick={dismiss}
            className="btn-ghost p-2 text-surface-500 hover:text-surface-700 dark:hover:text-surface-300"
            aria-label="Skip onboarding"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 space-y-5">
          <div
            className={cn(
              "w-14 h-14 rounded-2xl flex items-center justify-center",
              step.gradient ? `bg-gradient-to-br ${step.gradient}` : "bg-brand-100 dark:bg-brand-900/30"
            )}
          >
            <Icon
              className={cn(
                "w-7 h-7",
                step.gradient ? "text-white" : "text-brand-600 dark:text-brand-400"
              )}
            />
          </div>
          <div>
            <h2 id="onboarding-title" className="text-xl font-semibold text-surface-900 dark:text-surface-100">
              {step.title}
            </h2>
            <p className="text-sm text-brand-600 dark:text-brand-400 font-medium mt-1">
              {step.subtitle}
            </p>
          </div>
          <p id="onboarding-description" className="text-sm text-surface-600 dark:text-surface-400 leading-relaxed">
            {step.description}
          </p>
          {step.features && (
            <ul className="space-y-2">
              {step.features.map((f, i) => (
                <li key={i} className="flex items-center gap-2 text-sm text-surface-600 dark:text-surface-400">
                  <span className="w-1.5 h-1.5 rounded-full bg-brand-500" />
                  {f}
                </li>
              ))}
            </ul>
          )}
        </div>

        {/* Footer */}
        <div className="p-5 pt-0 flex flex-col sm:flex-row items-center justify-between gap-4 border-t border-surface-200 dark:border-surface-700">
          <div className="flex items-center gap-2">
            {steps.map((_, i) => (
              <button
                key={i}
                type="button"
                onClick={() => setCurrentStep(i)}
                className={cn(
                  "w-2 h-2 rounded-full transition-all",
                  i === currentStep
                    ? "bg-brand-600 w-6"
                    : "bg-surface-300 dark:bg-surface-600 hover:bg-surface-400"
                )}
                aria-label={`Go to step ${i + 1}`}
                aria-current={i === currentStep ? "step" : undefined}
              />
            ))}
          </div>
          <div className="flex items-center gap-2 w-full sm:w-auto">
            {!isFirst && (
              <button
                type="button"
                onClick={prev}
                className="btn-secondary"
              >
                <ChevronLeft className="w-4 h-4" />
                Back
              </button>
            )}
            {isLast ? (
              <Link
                href="/dashboard"
                onClick={dismiss}
                className="btn-primary flex-1 sm:flex-none"
              >
                Get Started
                <Monitor className="w-4 h-4" />
              </Link>
            ) : (
              <button type="button" onClick={next} className="btn-primary flex-1 sm:flex-none">
                Next
                <ChevronRight className="w-4 h-4" />
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
