/**
 * Initialize Turso DB: create tables and seed with mock data.
 * Run: npm run db:init
 * Requires TURSO_DATABASE_URL and TURSO_AUTH_TOKEN (optional for file: DB)
 */
import { createClient } from "@libsql/client";
import { config } from "dotenv";
import path from "path";

// Load .env from project root (where package.json is), regardless of cwd
const projectRoot = path.resolve(process.cwd());
config({ path: path.join(projectRoot, ".env.local") });
config({ path: path.join(projectRoot, ".env") });

// Trim to avoid BOM/whitespace issues; empty string should fallback
const envUrl = (process.env.TURSO_DATABASE_URL ?? "").trim();
const url =
  envUrl || `file:${path.join(projectRoot, "data", "local.db")}`;
const authToken = (process.env.TURSO_AUTH_TOKEN ?? "").trim() || undefined;

if (!url.startsWith("libsql://")) {
  console.warn(
    "⚠ TURSO_DATABASE_URL not set or invalid. Using local file DB. Set TURSO_DATABASE_URL in .env for Turso cloud."
  );
}

const client = createClient({ url, authToken });

const CREATE_WORKFLOWS = `
CREATE TABLE IF NOT EXISTS workflows (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  source TEXT NOT NULL,
  version TEXT NOT NULL,
  execution_time INTEGER NOT NULL,
  model TEXT NOT NULL,
  recording_id TEXT,
  tags TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
)`;

const CREATE_WORKFLOW_STEPS = `
CREATE TABLE IF NOT EXISTS workflow_steps (
  id TEXT PRIMARY KEY,
  workflow_id TEXT NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
  "order" INTEGER NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT NOT NULL
)`;

const CREATE_RECORDINGS = `
CREATE TABLE IF NOT EXISTS recordings (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  duration INTEGER NOT NULL,
  size INTEGER NOT NULL,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL
)`;

const CREATE_COMMENTS = `
CREATE TABLE IF NOT EXISTS comments (
  id TEXT PRIMARY KEY,
  workflow_id TEXT NOT NULL,
  comment TEXT NOT NULL,
  recording_id TEXT,
  created_at TEXT NOT NULL
)`;

const CLEAR_AND_SEED = `
DELETE FROM comments;
DELETE FROM workflow_steps;
DELETE FROM workflows;
DELETE FROM recordings;

-- Seed workflows
INSERT INTO workflows (id, title, description, source, version, execution_time, model, recording_id, tags, created_at, updated_at) VALUES
  ('wf_001', 'User Onboarding Flow — v2.4', 'Automated onboarding sequence generated by Opus that walks new users through account setup, preference configuration, and first-project creation.', 'Opus', '2.4.0', 3420, 'opus-4', 'rec_001', '["onboarding","user-flow","critical-path"]', '2026-02-15T08:30:00Z', '2026-02-15T09:15:00Z'),
  ('wf_002', 'Data Export Pipeline', 'OpenJarvis-generated workflow for exporting user analytics data to CSV and PDF formats with scheduled delivery.', 'OpenJarvis', '1.8.2', 8750, 'claw-v3', NULL, '["data","export","analytics"]', '2026-02-14T14:20:00Z', '2026-02-14T16:45:00Z'),
  ('wf_003', 'Permission Escalation Review', 'Opus-generated audit workflow for reviewing and approving permission escalation requests from team members.', 'Opus', '3.1.0', 1200, 'opus-4', 'rec_002', '["security","permissions","audit"]', '2026-02-13T10:00:00Z', '2026-02-13T10:30:00Z'),
  ('wf_004', 'Invoice Generation & Delivery', 'End-to-end invoice creation workflow from OpenJarvis, covering line item assembly through client delivery via email.', 'OpenJarvis', '2.0.1', 5200, 'claw-v3', NULL, '["billing","invoices","finance"]', '2026-02-12T16:00:00Z', '2026-02-12T17:30:00Z');

-- Seed workflow steps
INSERT INTO workflow_steps (id, workflow_id, "order", title, description, status) VALUES
  ('wf_001_s1', 'wf_001', 1, 'Welcome Modal Displayed', 'System triggers the welcome modal after successful email verification. Includes brand animation and CTA.', 'completed'),
  ('wf_001_s2', 'wf_001', 2, 'Profile Setup Form', 'User fills in display name, avatar upload, and timezone selection. Validation runs on blur.', 'completed'),
  ('wf_001_s3', 'wf_001', 3, 'Workspace Configuration', 'Prompt user to name their workspace, invite teammates, and select a color theme.', 'completed'),
  ('wf_001_s4', 'wf_001', 4, 'First Project Creation', 'Guide user through creating their first project using a template or blank canvas.', 'pending'),
  ('wf_001_s5', 'wf_001', 5, 'Completion & Dashboard Redirect', 'Show success confetti, then redirect to the main dashboard with a contextual tooltip tour.', 'pending'),
  ('wf_002_s1', 'wf_002', 1, 'Select Date Range', 'User selects export date range via calendar picker. Supports preset ranges (7d, 30d, 90d, custom).', 'completed'),
  ('wf_002_s2', 'wf_002', 2, 'Choose Export Format', 'Toggle between CSV, PDF, and JSON. Each format shows a live preview of column mapping.', 'completed'),
  ('wf_002_s3', 'wf_002', 3, 'Configure Filters', 'Optional step to filter by team, project, or user role before export.', 'completed'),
  ('wf_002_s4', 'wf_002', 4, 'Queue Export Job', 'Submit the export job to the background processor. Show progress indicator and estimated time.', 'failed'),
  ('wf_002_s5', 'wf_002', 5, 'Download or Email Delivery', 'Once processing completes, offer direct download or email delivery with a signed link.', 'pending'),
  ('wf_003_s1', 'wf_003', 1, 'Request Submitted', 'Team member submits permission escalation request with justification and scope definition.', 'completed'),
  ('wf_003_s2', 'wf_003', 2, 'Automated Risk Assessment', 'System analyzes the requested permissions against security policies and flags potential risks.', 'completed'),
  ('wf_003_s3', 'wf_003', 3, 'Manager Review', 'Direct manager receives notification and reviews the request with risk assessment context.', 'completed'),
  ('wf_003_s4', 'wf_003', 4, 'Security Team Approval', 'For high-risk escalations, the security team performs a secondary review.', 'completed'),
  ('wf_003_s5', 'wf_003', 5, 'Permission Applied', 'Approved permissions are applied with an automatic 90-day expiry and audit trail entry.', 'completed'),
  ('wf_004_s1', 'wf_004', 1, 'Pull Billable Items', 'Aggregate all billable items from the selected time period across projects and contracts.', 'completed'),
  ('wf_004_s2', 'wf_004', 2, 'Apply Rates & Discounts', 'Calculate totals using contracted rates, apply any volume discounts or credits.', 'completed'),
  ('wf_004_s3', 'wf_004', 3, 'Generate PDF Invoice', 'Render the invoice PDF with company branding, line items, tax calculations, and payment terms.', 'pending'),
  ('wf_004_s4', 'wf_004', 4, 'Send to Client', 'Email the invoice to the client''s billing contact with a payment portal link.', 'pending');

-- Seed recordings
INSERT INTO recordings (id, name, duration, size, status, created_at) VALUES
  ('rec_001', 'Onboarding Flow Walkthrough', 245, 48500000, 'uploaded', '2026-02-15T08:00:00Z'),
  ('rec_002', 'Permission Escalation Demo', 180, 32100000, 'uploaded', '2026-02-13T09:30:00Z'),
  ('rec_003', 'Dashboard Bug Reproduction', 67, 12800000, 'ready', '2026-02-11T14:15:00Z');
`;

// Split by ";", trim, remove empty - but keep statements that have "--" comments inside them
// (only filter statements that are ONLY a comment)
const seedStatements = CLEAR_AND_SEED.split(";")
  .map((s) => s.trim())
  .filter((s) => s.length > 0 && s !== "--");

const STATEMENTS = [
  CREATE_WORKFLOWS,
  CREATE_WORKFLOW_STEPS,
  CREATE_RECORDINGS,
  CREATE_COMMENTS,
  ...seedStatements,
];

async function main() {
  console.log("Initializing Turso DB...");
  console.log("Using:", url.startsWith("libsql://") ? "Turso (cloud)" : url);

  for (const stmt of STATEMENTS) {
    const trimmed = stmt.trim();
    if (!trimmed) continue;
    await client.execute(trimmed);
  }

  const { rows } = await client.execute("SELECT COUNT(*) as c FROM workflows");
  const count = Number(rows[0]?.c ?? 0);
  if (count === 0 && url.startsWith("libsql://")) {
    console.warn("⚠ Verification failed: 0 workflows in DB. Data may not have been written to Turso.");
    process.exit(1);
  }

  console.log(`Done. Tables created and seeded. (workflows: ${count})`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
